import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {api,CATS,inr} from './api.js';
const blank={name:'',category:CATS[0],price:'',mrp:'',moq:1,fabric:'',work:'',rating:4.5,badge:'',image:'',active:true,hot:false};
const ST=['placed','confirmed','shipped','delivered','cancelled'];
export default function Admin(){
const[ok,setOk]=useState(!!localStorage.getItem('xyz_token'));const[cr,setCr]=useState({email:'',password:''});const[err,setErr]=useState('');const[tab,setTab]=useState('stats');const[d,setD]=useState({});const[f,setF]=useState(blank);const[eid,setEid]=useState(null);const[pt,setPt]=useState({title:'',excerpt:'',image:'',body:''});
const out=()=>{localStorage.removeItem('xyz_token');setOk(false)};
const load=t=>api(t==='stats'?'/admin/stats':'/admin/'+t).then(r=>setD(x=>({...x,[t]:r}))).catch(e=>e.message==='Unauthorized'&&out());
useEffect(()=>{ok&&load(tab)},[ok,tab]);
const login=async e=>{e.preventDefault();try{const r=await api('/login',{method:'POST',body:cr});localStorage.setItem('xyz_token',r.token);setOk(true)}catch(x){setErr(x.message)}};
const patch=async(m,id,b)=>{await api(`/admin/${m}/${id}`,{method:'PATCH',body:b});load(m)};
const del=async(m,id)=>{if(confirm('Delete this?')){await api(`/admin/${m}/${id}`,{method:'DELETE'});load(m)}};
const save=async e=>{e.preventDefault();const{_id,...rest}=f;const b={...rest,price:+f.price,mrp:+f.mrp||0,moq:+f.moq,rating:+f.rating};try{eid?await api('/admin/products/'+eid,{method:'PATCH',body:b}):await api('/admin/products',{method:'POST',body:b});setF(blank);setEid(null);setErr('');load('products')}catch(x){setErr(x.message)}};
if(!ok)return<div className="ad-login"><form onSubmit={login}><h2>Admin sign in</h2><input placeholder="Email" onChange={e=>setCr({...cr,email:e.target.value})}/><input type="password" placeholder="Password" onChange={e=>setCr({...cr,password:e.target.value})}/><button className="btn">Sign in</button>{err&&<p className="err">{err}</p>}<Link to="/">← Back to store</Link></form></div>;
const s=d.stats||{};const T=({h,children})=><div className="tw"><table><thead><tr>{h.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
const dt=x=>new Date(x).toLocaleDateString('en-IN');
return<div className="adm"><aside><b>XYZ</b>{[['stats','Dashboard'],['products','Products'],['orders','Orders'],['inquiries','Inquiries'],['subscribers','Subscribers'],['posts','Blog']].map(([k,l])=><button key={k} className={tab===k?'on':''} onClick={()=>setTab(k)}>{l}</button>)}<Link to="/">View store</Link><button onClick={out}>Log out</button></aside>
<main>{tab==='stats'&&<><h2>Dashboard</h2><div className="stats"><div><b>{inr(s.revenue)}</b>Revenue</div><div><b>{s.orders}</b>Orders</div><div><b>{s.newOrders}</b>New orders</div><div><b>{s.products}</b>Products</div><div><b>{s.inquiries}</b>New inquiries</div><div><b>{s.subscribers}</b>Subscribers</div></div></>}
{tab==='products'&&<><h2>Products</h2><form className="pf" onSubmit={save}>{[['name','Name'],['fabric','Fabric'],['work','Work'],['badge','Badge (Best Seller)'],['image','Image URL'],['mrp','Old price ₹ (strikethrough)','number'],['price','Price ₹','number'],['moq','MOQ','number'],['rating','Rating','number']].map(([k,p,t])=><input key={k} type={t||'text'} step="any" required={['name','price','image','moq'].includes(k)} placeholder={p} value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}
<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select><label><input type="checkbox" style={{width:'auto'}} checked={f.active} onChange={e=>setF({...f,active:e.target.checked})}/> Visible in store</label><label><input type="checkbox" style={{width:'auto'}} checked={!!f.hot} onChange={e=>setF({...f,hot:e.target.checked})}/> Hot selling</label><button className="btn">{eid?'Save changes':'Add product'}</button>{eid&&<button type="button" className="btn light" onClick={()=>{setF(blank);setEid(null)}}>Cancel</button>}{err&&<span className="err">{err}</span>}</form>
<T h={['','Name','Category','Price','MOQ','Status','']}>{(d.products||[]).map(p=><tr key={p._id}><td><img src={p.image} alt=""/></td><td>{p.name}</td><td>{p.category}</td><td>{inr(p.price)}</td><td>{p.moq}</td><td>{p.active?'Live':'Hidden'}</td><td><button onClick={()=>{setEid(p._id);setF(p);scrollTo(0,0)}}>Edit</button><button onClick={()=>patch('products',p._id,{active:!p.active})}>{p.active?'Hide':'Show'}</button><button onClick={()=>del('products',p._id)}>Delete</button></td></tr>)}</T></>}
{tab==='orders'&&<><h2>Orders</h2><T h={['Order','Date','Customer','Items','Total','Payment','Status','']}>{(d.orders||[]).map(o=><tr key={o._id}><td><b>{o.orderNo}</b></td><td>{dt(o.createdAt)}</td><td>{o.customer.name}<br/>{o.customer.phone}<br/>{o.customer.address}, {o.customer.city} {o.customer.pincode}</td><td>{o.items.map(i=><div key={i.product}>{i.name} × {i.qty}</div>)}</td><td>{inr(o.total)}</td><td>{o.payment}</td><td><select value={o.status} onChange={e=>patch('orders',o._id,{status:e.target.value})}>{ST.map(x=><option key={x}>{x}</option>)}</select></td><td><button onClick={()=>del('orders',o._id)}>Delete</button></td></tr>)}</T></>}
{tab==='inquiries'&&<><h2>Inquiries</h2><T h={['Date','Name','Phone','Email','Collection','Message','Status','']}>{(d.inquiries||[]).map(i=><tr key={i._id}><td>{dt(i.createdAt)}</td><td>{i.name}</td><td>{i.phone}</td><td>{i.email}</td><td>{i.collection}</td><td>{i.message}</td><td><select value={i.status} onChange={e=>patch('inquiries',i._id,{status:e.target.value})}><option>new</option><option>contacted</option><option>closed</option></select></td><td><button onClick={()=>del('inquiries',i._id)}>Delete</button></td></tr>)}</T></>}
{tab==='subscribers'&&<><h2>Subscribers</h2><T h={['Date','Email','']}>{(d.subscribers||[]).map(x=><tr key={x._id}><td>{dt(x.createdAt)}</td><td>{x.email}</td><td><button onClick={()=>del('subscribers',x._id)}>Delete</button></td></tr>)}</T></>}
{tab==='posts'&&<><h2>Blog</h2><form className="pf" onSubmit={async e=>{e.preventDefault();await api('/admin/posts',{method:'POST',body:pt});setPt({title:'',excerpt:'',image:'',body:''});load('posts')}}>{['title','excerpt','image','body'].map(k=><input key={k} required placeholder={k==='image'?'image URL':k} value={pt[k]} onChange={e=>setPt({...pt,[k]:e.target.value})}/>)}<button className="btn">Publish</button></form><T h={['Date','Title','']}>{(d.posts||[]).map(x=><tr key={x._id}><td>{dt(x.createdAt)}</td><td>{x.title}</td><td><button onClick={()=>del('posts',x._id)}>Delete</button></td></tr>)}</T></>}
</main></div>}
