import {useEffect,useMemo,useState} from 'react';import {Link} from 'react-router-dom';import {api,inr,CATS,FREE_SHIP,SHIP,WA} from './api.js';
const ld=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const U=(id,w)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;
const form=e=>{e.preventDefault();return Object.fromEntries(new FormData(e.target))};
const CARES=[['✦','Best Quality','Fabric checked from cutting to final finish.'],['☎','Call Support','Talk to our team directly for rates and designs.'],['✈','Worldwide Shipping','Bulk dispatch from Surat to India and abroad.'],['✂','Customization & Labeling','Your brand label, tags and packaging.']];
const CI=[['Readymade Suits','/media/suit-blue.jpg'],['Co-ord Sets','/media/coord.jpg'],['Kaftans','/media/kaftan.jpg'],['Tops & Western','/media/tops.jpg']];
const IG=['/media/suit-red.jpg','/media/group.jpg','/media/suit-teal.jpg','/media/coord.jpg','/media/tops.jpg','/media/suit-blue.jpg'];
const Logo=()=><a className="logo" href="#home">X<i>Y</i>Z</a>;
export default function Shop(){
const[products,setProducts]=useState([]);const[posts,setPosts]=useState([]);const[cat,setCat]=useState('Hot');const[cart,setCart]=useState(()=>ld('xyz_cart',[]));const[wish,setWish]=useState(()=>ld('xyz_wish',[]));
const[view,setView]=useState('');const[menu,setMenu]=useState(false);const[toast,setToast]=useState('');const[order,setOrder]=useState(null);const[err,setErr]=useState('');const[pay,setPay]=useState('COD');const[more,setMore]=useState(false);const[post,setPost]=useState(null);
useEffect(()=>{api('/products').then(setProducts).catch(()=>setToast('Could not load products. Is the server running?'));api('/posts').then(setPosts).catch(()=>{})},[]);
useEffect(()=>localStorage.setItem('xyz_cart',JSON.stringify(cart)),[cart]);useEffect(()=>localStorage.setItem('xyz_wish',JSON.stringify(wish)),[wish]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)}},[toast]);
const list=useMemo(()=>products.filter(p=>cat==='Hot'?p.hot:p.category===cat),[products,cat]);
const add=p=>{setCart(c=>c.find(x=>x.id===p._id)?c.map(x=>x.id===p._id?{...x,qty:x.qty+1}:x):[...c,{id:p._id,name:p.name,price:p.price,image:p.image,moq:p.moq,qty:p.moq}]);setToast('Added to cart');setView('cart')};
const step=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(x.moq,x.qty+d)}:x));const rm=id=>setCart(c=>c.filter(x=>x.id!==id));
const subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0),shipping=subtotal&&subtotal<FREE_SHIP?SHIP:0,total=subtotal+shipping,count=cart.reduce((a,i)=>a+i.qty,0);
const tw=id=>{setToast(wish.includes(id)?'Removed from wishlist':'Saved to wishlist');setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id])};
const place=async e=>{const c=form(e);setErr('');try{const o=await api('/orders',{method:'POST',body:{customer:c,payment:pay,items:cart.map(({id,qty})=>({id,qty}))}});setOrder(o);setCart([]);setView('done')}catch(x){setErr(x.message)}};
const inquiry=async e=>{try{await api('/inquiries',{method:'POST',body:form(e)});e.target.reset();setView('');setToast('Inquiry sent. We will contact you soon.')}catch(x){setErr(x.message)}};
const subscribe=async e=>{const{email}=form(e);try{await api('/subscribe',{method:'POST',body:{email}});e.target.reset();setToast('Thanks for subscribing')}catch(x){setToast(x.message)}};
const X=({onClick})=><button className="close" style={{position:'static'}} onClick={onClick} aria-label="Close">×</button>;
return<>
<div className="topbar">WHOLESALE LADIES READYMADE GARMENTS • SURAT • WORLDWIDE SHIPPING</div>
<header><div className="container nav"><Logo/><nav className={'links'+(menu?' open':'')} onClick={()=>setMenu(false)}><a href="#home">Home</a><a href="#products">Hot Selling</a><a href="#about">About</a><a href="#blog">Blog</a><a href="#instagram">Instagram</a><a href="#contact">Contact</a></nav>
<div className="actions"><Link className="icon-btn" to="/admin" title="Admin" style={{display:'grid',placeItems:'center'}}>♙</Link>
<button className="icon-btn" title="Wishlist" onClick={()=>setView('wish')}>♡{wish.length>0&&<span className="badge-n">{wish.length}</span>}</button>
<button className="icon-btn" title="Cart" onClick={()=>setView('cart')}>🛒{cart.length>0&&<span className="badge-n">{cart.length}</span>}</button>
<button className="btn dark" onClick={()=>setView('inq')}>Wholesale Inquiry</button><button className="icon-btn hamb" onClick={()=>setMenu(!menu)} aria-label="Menu">☰</button></div></div></header>
<main>
<section className="hero-video" id="home" aria-label="XYZ collection video"><video src="/media/hero.mp4" poster="/media/hero-poster.jpg" autoPlay muted loop playsInline preload="auto" aria-hidden="true"/></section>
<div className="container cares"><div className="cares-h" style={{color:'#fff',position:'absolute',top:-70,left:0,right:0}}>XYZ Cares</div><div className="cares-grid">{CARES.map(([i,t,d])=><div className="care" key={t}><div className="ic">{i}</div><h3>{t}</h3><p>{d}</p></div>)}</div></div>
<section className="catsec"><div className="container"><div className="catcards">{CI.map(([c,i])=><a key={c} className="catcard" href="#products" onClick={()=>setCat(c)}><img src={i} alt={c} loading="lazy"/><span>{c}</span></a>)}</div></div></section>
<section id="products"><div className="container"><div className="sh"><div className="eyebrow">Trending now</div><h2>Hot Selling Products</h2><p>Best sellers loved by retailers across India. Prices are per piece.</p></div>
<div className="tabs">{['Hot',...CATS].map(c=><button key={c} className={'tab'+(cat===c?' on':'')} onClick={()=>setCat(c)}>{c==='Hot'?'Hot Selling':c}</button>)}</div>
<div className="products">{list.map(p=><article className="product" key={p._id}><div className="pimg"><img src={p.image} alt={p.name} loading="lazy"/>{p.badge&&<span className="tag">{p.badge}</span>}{p.mrp>p.price&&<span className="off">-{Math.round((1-p.price/p.mrp)*100)}%</span>}<button className="wl" aria-label="Wishlist" onClick={()=>tw(p._id)}>{wish.includes(p._id)?'♥':'♡'}</button></div>
<div className="pbody"><h3>{p.name}</h3><div className="meta">{p.fabric} • {p.work}{p.moq>1&&` • MOQ ${p.moq} pcs`}</div><div className="prices"><b>{inr(p.price)}</b>{p.mrp>p.price&&<s>{inr(p.mrp)}</s>}</div><button className="btn dark" onClick={()=>add(p)}>Add to Cart</button></div></article>)}</div>
{!list.length&&<p className="empty">No products in this category yet.</p>}</div></section>
<section className="about" id="about"><div className="container about-grid"><div className="about-img"><img src="/media/group.jpg" alt="XYZ collection" style={{objectPosition:'top'}}/></div><div><div className="eyebrow">About us</div><h2>XYZ: Redefining Ladies Fashion Wholesale from Surat</h2><p>Welcome to XYZ, Surat's leading name in ladies' readymade garment manufacturing. With a passion for quality and a commitment to excellence, we craft a wide range of stylish and premium garments, including kurtis, readymade suits, gowns and co-ord sets.</p>
{more&&<p>Every style goes through fabric checking, stitching supervision and final inspection. We support low order quantities, custom labeling and safe bulk packing, so retailers and wholesalers can grow with a supplier they can rely on.</p>}
<div className="stats2"><div><b>1,000+</b><span>Wholesalers &amp; Retailers Trust</span></div><div><b>10,000+</b><span>Quality Products</span></div></div><button className="btn dark" onClick={()=>setMore(!more)}>{more?'Show Less':'Learn More'} →</button></div></div></section>
<section id="blog"><div className="container"><div className="sh"><div className="eyebrow">Journal</div><h2>Our Blog</h2></div><div className="blog">{posts.map(p=><article className="post" key={p._id} tabIndex={0} onClick={()=>setPost(p)} onKeyDown={e=>e.key==='Enter'&&setPost(p)}><img src={p.image} alt=""/><div><small>{p.author} • {new Date(p.createdAt).toLocaleDateString('en-IN')}</small><h3>{p.title}</h3><p>{p.excerpt}</p><span className="meta">Read more →</span></div></article>)}</div></div></section>
<section className="insta" id="instagram"><div className="container"><div className="sh"><div className="eyebrow">Follow along</div><h2>Our Instagram</h2><p><a href="https://www.instagram.com/" target="_blank" rel="noreferrer">@xyz.india</a></p></div><div className="ig">{IG.map(i=><a key={i} href="https://www.instagram.com/" target="_blank" rel="noreferrer"><img src={i} alt="Instagram post" loading="lazy"/></a>)}</div></div></section>
<section><div className="container"><div className="sh"><div className="eyebrow">Testimonials</div><h2>Loved by our partners</h2></div><div className="reviews">{[['Amazing quality and designs! My customers love the variety XYZ offers.','Divyesh Malhotra'],['Great fabric, on-time delivery and factory pricing. A dependable wholesale partner.','Mital Poonawala']].map(([t,n])=><blockquote key={n}><div className="stars">★★★★★</div>“{t}”<footer>{n}</footer></blockquote>)}</div></div></section>
</main>
<div className="cta" id="contact"><div className="container cta-row"><div><h2>Ready to stock your store?</h2><p>Get rates, catalogues and custom labeling details on call or WhatsApp.</p></div><div className="hero-actions"><a className="btn" target="_blank" rel="noreferrer" href={`https://wa.me/${WA}`}>Chat on WhatsApp</a><button className="btn light" onClick={()=>setView('inq')}>Send Inquiry</button></div></div></div>
<div className="newsletter"><div className="container nl"><div><h3>Stay updated</h3><p className="meta">New arrivals and offers straight to your inbox.</p></div><form onSubmit={subscribe}><input name="email" type="email" required placeholder="Your email address" aria-label="Email"/><button>Subscribe</button></form></div></div>
<footer><div className="container"><div className="fg"><div><Logo/><p>Surat's ladies readymade garments manufacturer for wholesalers and retailers.</p></div><div><h4>Explore</h4><a href="#products">Hot Selling</a><a href="#about">About</a><a href="#blog">Blog</a><a href="#instagram">Instagram</a></div><div><h4>Collections</h4>{CATS.map(c=><a key={c} href="#products" onClick={()=>setCat(c)}>{c}</a>)}</div><div><h4>Contact</h4><p>+91 99999 99999</p><p>info@xyz.com</p><p>Surat, Gujarat, India</p></div></div><div className="copy">© 2026 XYZ. All rights reserved.</div></div></footer>

{view==='cart'&&<><div className="overlay" onClick={()=>setView('')}/><aside className="drawer"><h2>Your Cart ({count} pcs)<X onClick={()=>setView('')}/></h2>
<div className="list">{cart.length?cart.map(i=><div className="ci" key={i.id}><img src={i.image} alt=""/><div><b>{i.name}</b><div className="meta">{inr(i.price)} / pc{i.moq>1&&` • MOQ ${i.moq}`}</div><div className="qty"><button onClick={()=>step(i.id,-1)} aria-label="Less">−</button>{i.qty}<button onClick={()=>step(i.id,1)} aria-label="More">+</button><b style={{marginLeft:10}}>{inr(i.price*i.qty)}</b><button className="rm" style={{border:0,width:'auto'}} onClick={()=>rm(i.id)}>Remove</button></div></div></div>):<p className="empty">Your cart is empty.</p>}</div>
{cart.length>0&&<div className="sum"><div><span>Subtotal</span><span>{inr(subtotal)}</span></div><div><span>Shipping</span><span>{shipping?inr(shipping):'Free'}</span></div>{shipping>0&&<small className="meta">Add {inr(FREE_SHIP-subtotal)} more for free shipping</small>}<div className="tot"><span>Total</span><span>{inr(total)}</span></div><button className="btn dark" onClick={()=>{setErr('');setView('checkout')}}>Proceed to Checkout →</button></div>}</aside></>}
{view==='wish'&&<><div className="overlay" onClick={()=>setView('')}/><aside className="drawer"><h2>Wishlist<X onClick={()=>setView('')}/></h2><div className="list">{products.filter(p=>wish.includes(p._id)).map(p=><div className="ci" key={p._id}><img src={p.image} alt=""/><div><b>{p.name}</b><div className="meta">{inr(p.price)} / pc</div><div className="qty"><button className="small-btn" style={{width:'auto',padding:'4px 12px',borderRadius:6}} onClick={()=>{add(p);tw(p._id)}}>Move to cart</button><button className="rm" style={{border:0,width:'auto'}} onClick={()=>tw(p._id)}>Remove</button></div></div></div>)}{!wish.length&&<p className="empty">No saved styles yet. Tap ♡ on a product.</p>}</div></aside></>}
{view==='checkout'&&<div className="modal open" onClick={e=>e.target===e.currentTarget&&setView('')}><div className="modal-box"><button className="close" onClick={()=>setView('')}>×</button><div className="eyebrow">Secure Checkout</div><h2>Delivery details</h2>
<form className="form" onSubmit={place}><input name="name" required placeholder="Full name / Business name"/><input name="phone" required type="tel" pattern="[0-9+ ]{10,14}" placeholder="Phone / WhatsApp"/><input name="email" type="email" placeholder="Email (optional)"/><textarea name="address" required placeholder="Full address"/><input name="city" required placeholder="City"/><input name="pincode" required pattern="[0-9]{6}" placeholder="Pincode (6 digits)"/>
<select value={pay} onChange={e=>setPay(e.target.value)}><option value="COD">Cash on Delivery</option><option value="Bank Transfer">Bank / UPI transfer (we will send details)</option></select>
<div className="sum" style={{padding:0,border:0}}><div><span>{cart.length} styles, {count} pcs</span><span>{inr(subtotal)}</span></div><div><span>Shipping</span><span>{shipping?inr(shipping):'Free'}</span></div><div className="tot"><span>Total</span><span>{inr(total)}</span></div></div>{err&&<p className="err">{err}</p>}<button className="btn">Place Order →</button></form></div></div>}
{view==='done'&&order&&<div className="modal open"><div className="modal-box ok-box"><div className="big">✓</div><h2>Order placed!</h2><p>Order no. <b>{order.orderNo}</b></p><p className="meta" style={{margin:'8px 0 16px'}}>Total {inr(order.total)} • {order.payment}. Our team will call you to confirm.</p><div className="hero-actions" style={{justifyContent:'center'}}><a className="btn dark" target="_blank" rel="noreferrer" href={`https://wa.me/${WA}?text=${encodeURIComponent('Hi, I placed order '+order.orderNo)}`}>Confirm on WhatsApp</a><button className="btn light" style={{color:'var(--em)'}} onClick={()=>setView('')}>Continue shopping</button></div></div></div>}
{view==='inq'&&<div className="modal open" onClick={e=>e.target===e.currentTarget&&setView('')}><div className="modal-box"><button className="close" onClick={()=>setView('')}>×</button><div className="eyebrow">Wholesale Inquiry</div><h2>Let's grow together</h2>
<form className="form" onSubmit={inquiry}><input name="name" required placeholder="Your name"/><input name="phone" required type="tel" placeholder="Phone / WhatsApp"/><input name="email" type="email" placeholder="Email"/><select name="collection"><option value="">Interested collection</option>{CATS.map(c=><option key={c}>{c}</option>)}</select><textarea name="message" placeholder="Tell us your requirement..."/>{err&&<p className="err">{err}</p>}<button className="btn">Send Inquiry →</button></form></div></div>}
{post&&<div className="modal open" onClick={e=>e.target===e.currentTarget&&setPost(null)}><div className="modal-box"><button className="close" onClick={()=>setPost(null)}>×</button><h2>{post.title}</h2><p style={{marginTop:14}}>{post.body||post.excerpt}</p></div></div>}
{toast&&<div className="toast" role="status">{toast}</div>}
</>}
